### ISSUE TITLE
Update dockerhub

### ISSUE THREAD

**Issue by peterbell10** [cuberite/docker-build-image#4]
The dockerhub builds are out of date:
https://hub.docker.com/r/cuberite/docker-build-image

I don't know who has access to that account (@bearbin maybe) but I think dockerhub can be set up to auto-build when the branch is changed.

**Comment by bearbin** [comment]
I don't have access, I think it's @sphinxc0re if anyone (see #1).

**Comment by sphinxc0re** [comment]
I can add ppl as members to the org on docker hub. You just have to give me your docker ID.

**Comment by peterbell10** [comment]
I think myself, @bearbin and @madmaxoft all have accounts with our github usernames.

**Comment by sphinxc0re** [comment]
Done, done and done :grin:

**Comment by peterbell10** [comment]
For some reason it wasn't letting me add the `circle-ci` branch to the autobuild rules. I've pushed it manually which is good enough for me.
